[[modes]]
name = "develop"
init_command = "devbox shell"
reactive_panes = 2

[[modes.panes]]
command = "git diff --stat HEAD"
name = "Changed Files"

[[modes.rules]]
pattern = "npm run (build|build:dev|build:prod)"
watch = false

[[modes.rules]]
pattern = "npm run test"
watch = false
