providers:
  google_secrets_manager:
    kind: google_secretmanager
    maps:
      - id: secrets
        path: projects/vfarcic
        keys:
          anthropic-api-key: ANTHROPIC_API_KEY
          qdrant-api-key: QDRANT_API_KEY
