# Gateway API - Basic HTTP Example
# Deploy dot-ai MCP server with HTTP-only Gateway API access

# Prerequisites:
# - Kubernetes 1.26+ cluster
# - Gateway API CRDs installed (kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml)
# - GatewayClass available (check with: kubectl get gatewayclass)
# - Gateway controller running (e.g., Istio, Envoy Gateway, Kong)

# Configuration:
# - HTTP listener on port 80
# - No TLS/HTTPS (HTTP only)
# - SSE streaming timeout: 3600s
# - Standard deployment method (Kubernetes resources)

---
# Example values.yaml for Helm installation
# Save this to a file (e.g., gateway-http-values.yaml) and use with:
#   helm install dot-ai oci://ghcr.io/vfarcic/dot-ai/charts/dot-ai:0.163.0 \
#     --namespace dot-ai \
#     --create-namespace \
#     -f gateway-http-values.yaml

# Deployment method
deployment:
  method: standard

# Disable traditional Ingress (mutually exclusive with Gateway API)
ingress:
  enabled: false

# Enable Gateway API
gateway:
  enabled: true
  className: "istio"  # CHANGE THIS: Use your GatewayClass name (istio, envoy-gateway, gke-l7-global-external-managed, etc.)
  
  # Optional: Annotations for integrations
  # Uncomment and configure as needed
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: "dot-ai.example.com"
  
  listeners:
    # HTTP listener (port 80)
    http:
      enabled: true
      hostname: "dot-ai.example.com"  # CHANGE THIS: Your hostname
    
    # HTTPS listener (disabled for HTTP-only deployment)
    https:
      enabled: false
  
  # SSE streaming timeouts (important for long-running connections)
  timeouts:
    request: "3600s"
    backendRequest: "3600s"

# Secrets configuration
# IMPORTANT: Either provide values here or create the secret manually before deployment
secrets:
  name: dot-ai-secrets
  
  # Bearer token for HTTP authentication
  # Generate with: openssl rand -base64 32
  auth:
    token: ""  # SET THIS: Your auth token
  
  # AI provider API keys
  anthropic:
    apiKey: ""  # SET THIS: sk-ant-api03-...
  
  openai:
    apiKey: ""  # SET THIS: sk-proj-... (required for embeddings)

# AI provider configuration
ai:
  provider: anthropic
  # Optional: Uncomment to use different model or custom endpoint
  # model: ""
  # customEndpoint:
  #   enabled: false
  #   baseURL: ""

# Qdrant vector database (included automatically)
qdrant:
  enabled: true

---
# Alternative: Create secret manually (if not providing values in secrets section above)
# This allows you to keep sensitive data out of values.yaml
# Apply with: kubectl apply -f -

apiVersion: v1
kind: Secret
metadata:
  name: dot-ai-secrets
  namespace: dot-ai
type: Opaque
stringData:
  # Generate auth token: openssl rand -base64 32
  auth-token: "REPLACE_WITH_YOUR_AUTH_TOKEN"
  
  # AI provider API keys
  anthropic-api-key: "sk-ant-api03-REPLACE_WITH_YOUR_KEY"
  openai-api-key: "sk-proj-REPLACE_WITH_YOUR_KEY"
  
  # Optional: Other provider API keys (if using different AI provider)
  # google-api-key: ""
  # xai-api-key: ""
  # moonshot-api-key: ""

---
# Installation Steps:

# 1. Verify prerequisites
echo "Checking Gateway API CRDs..."
kubectl get crd gateways.gateway.networking.k8s.io httproutes.gateway.networking.k8s.io

echo "Checking GatewayClass..."
kubectl get gatewayclass

# 2. Create namespace
kubectl create namespace dot-ai

# 3. Create secret (if not using values.yaml approach)
# Edit the secret above with your actual values, then apply:
# kubectl apply -f gateway-http-values.yaml  # (only the Secret part)

# 4. Install Helm chart
# Edit gateway-http-values.yaml (the values.yaml section above) with your configuration, then:
helm install dot-ai \
  oci://ghcr.io/vfarcic/dot-ai/charts/dot-ai:0.163.0 \
  --namespace dot-ai \
  --create-namespace \
  -f gateway-http-values.yaml \
  --wait

# 5. Verify deployment
kubectl get gateway,httproute,service,deployment -n dot-ai

# 6. Get Gateway IP/hostname
kubectl get gateway dot-ai -n dot-ai -o jsonpath='{.status.addresses[0].value}'

# 7. Configure DNS
# Point your hostname (dot-ai.example.com) to the Gateway IP from step 6
# Either manually create A record or use external-dns (see external-dns.yaml example)

# 8. Test the MCP server
# Replace dot-ai.example.com with your actual hostname
curl http://dot-ai.example.com/

# Test SSE endpoint
curl -N -H "Accept: text/event-stream" \
  -H "Authorization: Bearer YOUR_AUTH_TOKEN" \
  http://dot-ai.example.com/sse

---
# Troubleshooting:

# Gateway not getting IP address?
kubectl describe gateway dot-ai -n dot-ai
# Look for conditions and events

# HTTPRoute not routing traffic?
kubectl describe httproute dot-ai -n dot-ai
# Check parentRef matches Gateway name
# Check backend Service exists

# Connection timeouts?
# Verify timeout configuration in HTTPRoute:
kubectl get httproute dot-ai -n dot-ai -o yaml | grep -A 5 timeouts

# Cannot enable both ingress and gateway?
# This is expected - they are mutually exclusive
# Make sure ingress.enabled=false in values.yaml

---
# Next Steps:

# - For HTTPS with cert-manager: See https-cert-manager.yaml
# - For external-dns integration: See external-dns.yaml
# - For ToolHive deployment: Set deployment.method=toolhive
# - Full documentation: docs/setup/gateway-api-setup.md
